### PR TITLE
Adds support for version 1.2.0

### PR DESCRIPTION
**Pull request by ericbaum**
This commit makes minor changes to support version 1.2.0 from Mesos as requested on issue #128

### CODE REVIEW

**Comment by davidvonthenen** [comment]
Hi @ericbaum were you able to test the generated isolator? I think I recall @cantbewong mentioning that he was working on 1.2.0 and that it built but it didn't actually run when using a 1.2.0 mesos configuration? If you have, I would be glad to merge this.

**Comment by ericbaum** [comment]
Hello @dvonthenen we tested it and it is working on our scenario. We didn't do a variety of tests, but we found no problems so far.

The scenario comprises mesos-1.2.0 + marathon-1.4.1 + rexray + dvdi + ceph storage backend running docker containers.

We haven't tried it using mesos containerizer, just the docker containerizer. Further tests with mesos containerizers might be necessary to actually validate this change.

**Comment by davidvonthenen** [comment]
Thanks for the info @ericbaum Yea, the mesos-module-dvdi is only exercised when using the mesos containerizer. I have a bunch of work leading up to a conference next week, so I will be unable to test the change myself. I can test the following week however and let you know what I find.

**Comment by clintkitson** [comment]
@ericbaum Thanks for the contribution here. Curious as to what is driving you to continue to use the module since Mesos now has `dvdi` built in? This module was the precursor to `dvdi` and encompasses similar capabilities, and both methods actually leverage the `dvdcli` tool in the same way. Thank you!

**Comment by davidvonthenen** [comment]
@ericbaum talked it over and this is fairly low risk. Thanks for the contribution. Will test the following week before doing the release.

**Comment by grisaitis** [comment]
@clintkitson does mesos not depend on `dvdcli` anymore? [MESOS-4355](https://issues.apache.org/jira/browse/MESOS-4355), "Implement isolator for Docker volume", is still open. Sorry if I'm confusing `dvdi` and `dvdcli` -- not sure which things have been integrated into mesos at this time.

**Comment by clintkitson** [comment]
@grisaitis Yes, Mesos requires `dvdcli` with both this module and separately when using `dvdi`. They are two completely discrete methods of providing the volume functionality both using the same tool.

**Pull request merged**
