### PR TITLE
Issue 15 - Isolator Modernization to Mesos 0.24.X

### PR DESCRIPTION
**Pull request by davidvonthenen**
### Issue 15 - Isolator Modernization to Mesos 0.24.X

Brought the existing Isolator code base up from version 0.23.X to 0.24.X. Tested on a single standalone 0.24.1 node (master, slave, marathon with latest stable rexray and dvdcli).

Notable changes:
- IsolatorProcess class has been deprecated. Must implement and extend the Isolator class
- In receover() the object being passed in was of type ExecutorRunState but now it is of type ContainerState. The implement is similar but has some subtle differences
- In prepare(), the const Optionstd::string& rootfs parameter is no longer being passed into the function
- Update example in documentation to reflect the real Isolator string

### CODE REVIEW

**Comment by akutz** [comment]
Hi @dvonthenen,

You should almost never merge `upstream/master` but instead rebase your PR on top of it. I'm not sure that is related to the reason the build fails, but it will create a cleaner history enabling more expedient problem solving.

**Comment by davidvonthenen** [comment]
Hi @akutz,

The build failure is due to the fact that we need to upgrade the travis ci to use mesos 0.24.1. I will probably need to speak with you or someone else that is familiar with updating the ci infrastructure to point me in the right direction in order to make this change.

**Comment by akutz** [comment]
Hi @dvonthenen,

Hopefully our conversation this morning was able to shine a light on the Mesos build process and give you some idea of how to move forward. I'm building Mesos 0.24.1 now and will ping you once the 7z is cached.

**Comment by akutz** [comment]
Hi @dvonthenen,

Also, I looked at your changes, and I think the use of `#if MESOS_VERSION_INT >= 0240` or `< 0240` as we discussed would definitely work to preserve backwards compatibility.

**Comment by davidvonthenen** [comment]
Will start a new pull request.

**Pull request closed without merging**
