### PR TITLE
Add dvdcli parameter

### PR DESCRIPTION
**Pull request by branden**
This parameter sets the location of the dvdcli binary. Defaults to
`/usr/bin/dvdcli`.

### CODE REVIEW

**Comment by davidvonthenen** [comment]
Hi @branden 

I am interesting in hearing about the use case for making the DVDCLI location configurable. The DVDCLI installer defines where the binary is placed and I am curious as to what the motivation is for moving the binary?

Also, I would be a little nervous about making this fully qualified path configurable as one might be able to bootstrap another malicious binary in its place to potentially do a Man In The Middle data attack to snoop data. One could easily use a FUSE overlay to make that attack happen.

**Comment by clintkitson** [comment]
I think this makes a ton of sense as a configurable option when configuring
the Mesos agent with the isolator. A user configurable option of course
makes no sense.

@dvonthenen Maybe I am misinterpreting the PR here.

**Comment by branden** [comment]
Yeah, this is intended to be configured by an admin, in the same way as the existing `work_dir` config parameter.

> I am interesting in hearing about the use case for making the DVDCLI location configurable. The DVDCLI installer defines where the binary is placed and I am curious as to what the motivation is for moving the binary?

I'm installing DVDCLI under `/opt/` as part of another software package.

> Also, I would be a little nervous about making this fully qualified path configurable as one might be able to bootstrap another malicious binary in its place to potentially do a Man In The Middle data attack to snoop data. One could easily use a FUSE overlay to make that attack happen.

Setting this config value requires that you have admin privileges on the Mesos agent, so I'm not sure what vulnerability this adds. Can you explain the potential attack a bit more?

**Comment by jdef** [comment]
very interested in this feature. not sure how this is any less secure than the current implementation.

**Comment by davidvonthenen** [comment]
Apologize for letting this sit here as we have been busy with some internal commitments. We plan on having this in the next release. There currently is a conflict with this merge and I will hopefully get to this shortly.

**Comment by davidvonthenen** [comment]
@branden We took what was implemented in this PR and tried this out in a private build. It looks like that when you give the mesos agent a parameter that it isnt expecting, the agent fails to start up with an unknown parameter. I have seen this before when I fat finger running the agent on the command line versus as a service, when it receives a parameter it doesnt know about, the agent craps out. A quick test of this, just add a parameter called junk and set the value to myjunk. and you should see the same behavior.

I think rather than doing this as a parameter which **may** break in 0.30.0 because of a feature/functionality that is being deprecated in 0.30.0 (http://mail-archives.apache.org/mod_mbox/mesos-dev/201603.mbox/%3CCAK7AWaGB24ALh8eb+vKMFgc4+jmhxZ6ry79HBcKN+Bt04Sx43A@mail.gmail.com%3E), I think a solution that will work regardless of version and gives you even finer grain control would be to make this an environment variable that can be set per task and would support multiple dvdcli versions.

Since we are gearing up for a release soon, this reimplementation of this idea might not make it into the upcoming release. We will take it upon ourselves to implement in the next release however.

**Comment by clintkitson** [comment]
@dvonthenen Setting it as a DVDI_ environment variable does represent a very valid security risk. I would say implementing via something that agent respects like a local environment variable would be the best route.

**Comment by davidvonthenen** [comment]
@clintonskitson I agree there isnt anymore a security risk, then there is today with any of the other environment variables.

As for the local environment variable, I think I said that in my last comment and had agreed to implement it.

**Comment by clintkitson** [comment]
@dvonthenen the comment around "set per task" threw me off. This would I believe mean it was a choice from the task issuer.

**Comment by davidvonthenen** [comment]
@clintonskitson it can be done per task as described but since this is an environment variable, if the environment variable is set at the agent node level, you wouldn't need to specify it per task and it would automatically be inherit to every task. I was just trying to describe how granular you could potentially get.

I guess the interesting thing might be if both are set... we might want something to over the agent wide setting in favor for a more task specific one.

**Comment by davidvonthenen** [comment]
Will be closing this PR out as there is a new PR https://github.com/emccode/mesos-module-dvdi/pull/100 open that will resolve this issue along with other outstanding issues. Its a very close variant on your PR here.

**Comment by davidvonthenen** [comment]
The PR mentioned above has been merged. If this doesn't meet you requirements, we can revisit the issue.

**Pull request closed without merging**
